# Generated by Django 6.0.5 on 2026-06-12 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('observacoes', models.TextField(blank=True)),
                ('data_laudo', models.DateTimeField(auto_now_add=True)),
                ('exame', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exames.exame')),
            ],
        ),
    ]
