# Generated by Django 6.0.5 on 2026-06-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MEDICO', 'Médico'), ('USUARIO', 'Usuário'), ('SECRETARIA', 'Secretária')], default='USUARIO', max_length=10),
        ),
    ]
